/*
 * Mach Operating System
 * Copyright (c) 1991 Carnegie Mellon University
 * All Rights Reserved.
 *
 * This file would normally be generated by MIG from mach_host.defs.
 * This is a minimal stub for compilation.
 */

#ifndef	_MACH_HOST_H_INTERFACE_
#define	_MACH_HOST_H_INTERFACE_

#include <mach/mach_types.h>
#include <mach/host_info.h>
#include <mach/kern_return.h>

/* Type definitions used by host operations - must be before function declarations */
typedef char kernel_version_t[512];
typedef int mach_clock_id_t;
typedef mach_port_t mach_clock_t;
typedef natural_t mach_msg_type_number_t;

#ifdef __cplusplus
extern "C" {
#endif

/* Host operations - normally generated by MIG */

kern_return_t host_info(host_t host, host_flavor_t flavor,
                       host_info_t host_info_out,
                       mach_msg_type_number_t *host_info_outCnt);

kern_return_t host_kernel_version(host_t host, kernel_version_t kernel_version);

kern_return_t host_processor_info(host_t host, processor_flavor_t flavor,
                                  natural_t *out_processor_count,
                                  processor_info_array_t *out_processor_info,
                                  mach_msg_type_number_t *out_processor_infoCnt);

kern_return_t host_get_clock_service(host_t host, mach_clock_id_t clock_id,
                                     mach_clock_t *clock);

#ifdef __cplusplus
}
#endif

#endif	/* _MACH_HOST_H_INTERFACE_ */
