/*
 * Mach Operating System
 * Copyright (c) 1991 Carnegie Mellon University
 * All Rights Reserved.
 *
 * This file would normally be generated by MIG from mach_port.defs.
 * This is a minimal stub for compilation.
 */

#ifndef	_MACH_PORT_H_INTERFACE_
#define	_MACH_PORT_H_INTERFACE_

#include <mach/mach_types.h>
#include <mach/port.h>
#include <mach/kern_return.h>

/* Message type name - used in MIG-generated code */
typedef natural_t mach_msg_type_name_t;

#define MACH_MSG_TYPE_MOVE_RECEIVE	16	/* Must hold receive rights */
#define MACH_MSG_TYPE_MOVE_SEND		17	/* Must hold send rights */
#define MACH_MSG_TYPE_MOVE_SEND_ONCE	18	/* Must hold sendonce rights */
#define MACH_MSG_TYPE_COPY_SEND		19	/* Must hold send rights */
#define MACH_MSG_TYPE_MAKE_SEND		20	/* Must hold receive rights */
#define MACH_MSG_TYPE_MAKE_SEND_ONCE	21	/* Must hold receive rights */

#ifdef __cplusplus
extern "C" {
#endif

/* Port manipulation operations - normally generated by MIG */

kern_return_t mach_port_allocate(ipc_space_t task, mach_port_right_t right,
                                 mach_port_t *name);
kern_return_t mach_port_deallocate(ipc_space_t task, mach_port_t name);
kern_return_t mach_port_insert_right(ipc_space_t task, mach_port_t name,
                                     mach_port_t poly, mach_msg_type_name_t polyPoly);
kern_return_t mach_port_extract_right(ipc_space_t task, mach_port_t name,
                                      mach_msg_type_name_t msgt_name,
                                      mach_port_t *poly, mach_msg_type_name_t *polyPoly);

#ifdef __cplusplus
}
#endif

#endif	/* _MACH_PORT_H_INTERFACE_ */
