/*
 * Mach Operating System
 * Copyright (c) 1991 Carnegie Mellon University
 * All Rights Reserved.
 *
 * This file would normally be generated by MIG (Mach Interface Generator)
 * from mach.defs. This is a minimal stub for compilation.
 */

#ifndef	_MACH_INTERFACE_H_
#define	_MACH_INTERFACE_H_

#include <mach/mach_types.h>
#include <mach/kern_return.h>

/* Basic Mach calls - normally generated by MIG */

#ifdef __cplusplus
extern "C" {
#endif

/* Task operations */
kern_return_t task_create(task_t parent_task, boolean_t inherit_memory,
                         task_t *child_task);
kern_return_t task_terminate(task_t target_task);
kern_return_t task_suspend(task_t target_task);
kern_return_t task_resume(task_t target_task);

/* Thread operations */
kern_return_t thread_create(task_t parent_task, thread_t *child_thread);
kern_return_t thread_terminate(thread_t target_thread);
kern_return_t thread_suspend(thread_t target_thread);
kern_return_t thread_resume(thread_t target_thread);

/* VM operations */
kern_return_t vm_allocate(vm_task_t target_task, vm_address_t *address,
                         vm_size_t size, boolean_t anywhere);
kern_return_t vm_deallocate(vm_task_t target_task, vm_address_t address,
                           vm_size_t size);
kern_return_t vm_protect(vm_task_t target_task, vm_address_t address,
                        vm_size_t size, boolean_t set_maximum,
                        vm_prot_t new_protection);

#ifdef __cplusplus
}
#endif

#endif	/* _MACH_INTERFACE_H_ */
